// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmoSS24SRHOGKVfMBqOpWWY7DdNNAcFD4',
    appId: '1:401480613878:web:dfada163632d158cf8d1d7',
    messagingSenderId: '401480613878',
    projectId: 'push-notification-test-bf595',
    authDomain: 'push-notification-test-bf595.firebaseapp.com',
    storageBucket: 'push-notification-test-bf595.appspot.com',
    measurementId: 'G-KPYFZHGBF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPURjST0vUCK8vu8EY8Fd5LW9RfQHuixA',
    appId: '1:401480613878:android:349eb4cc85ea9d6af8d1d7',
    messagingSenderId: '401480613878',
    projectId: 'push-notification-test-bf595',
    storageBucket: 'push-notification-test-bf595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDab70h6i_MdKsY7wUJ31_WEffc25G5cRE',
    appId: '1:401480613878:ios:05ed5d84a7381210f8d1d7',
    messagingSenderId: '401480613878',
    projectId: 'push-notification-test-bf595',
    storageBucket: 'push-notification-test-bf595.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDab70h6i_MdKsY7wUJ31_WEffc25G5cRE',
    appId: '1:401480613878:ios:05ed5d84a7381210f8d1d7',
    messagingSenderId: '401480613878',
    projectId: 'push-notification-test-bf595',
    storageBucket: 'push-notification-test-bf595.appspot.com',
    iosBundleId: 'com.example.firebasePushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmoSS24SRHOGKVfMBqOpWWY7DdNNAcFD4',
    appId: '1:401480613878:web:73eaee170b432345f8d1d7',
    messagingSenderId: '401480613878',
    projectId: 'push-notification-test-bf595',
    authDomain: 'push-notification-test-bf595.firebaseapp.com',
    storageBucket: 'push-notification-test-bf595.appspot.com',
    measurementId: 'G-VJ6ZSRM6LE',
  );
}
